inherit_gem:
  percy-style:
    - default.yml
RSpec/InstanceVariable:
  Exclude:
    -
RSpec/ContextWording:
  Enabled: false
AllCops:
  TargetRubyVersion: 2.4
  Include:
    - lib/**/*.rb
    - spec/lib/**/*.rb
