require: rubocop-rspec
inherit_from: .rubocop_todo.yml
AllCops:
  Include:
    - Rakefile
    - lib/**/*.rake

Lint/EndAlignment:
  EnforcedStyleAlignWith: variable

Metrics/LineLength:
  Max: 100

Style/CaseIndentation:
  EnforcedStyle: end

Style/AlignParameters:
  EnforcedStyle: with_fixed_indentation

Style/Documentation:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Style/IndentArray:
  EnforcedStyle: consistent

Style/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Style/MultilineOperationIndentation:
  EnforcedStyle: indented

# Disable Style/NumericLiterals so numbers don't need underscores
Style/NumericLiterals:
  Enabled: false

Style/NumericPredicate:
  EnforcedStyle: comparison

Style/RedundantBegin:
  Enabled: false

Style/RegexpLiteral:
  EnforcedStyle: slashes
  AllowInnerSlashes: true

Style/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: consistent_comma

Style/TrailingCommaInLiteral:
  EnforcedStyleForMultiline: consistent_comma

RSpec/MessageSpies:
  EnforcedStyle: receive

# Will be able to do this in >= v1.11
# RSpec/DescribedClass:
#   EnforcedStyle: explicit
