require: rubocop-rspec
inherit_from: .rubocop_todo.yml
AllCops:
  Include:
    - Rakefile
    - lib/**/*.rake

Metrics/LineLength:
  Max: 100

Style/Documentation:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

RSpec/MessageSpies:
  EnforcedStyle: receive

# Will be able to do this in >= v1.11
# RSpec/DescribedClass:
#   EnforcedStyle: explicit
