language: ruby
sudo: false
cache: bundler
rvm:
  - ruby-2.2.6
  - ruby-2.3.3
  - ruby-2.4.0
  - ruby-head
matrix:
  allow_failures:
  - rvm: ruby-head
before_install:
  - gem update --system
  - gem update bundler
script:
  - xvfb-run bundle exec rspec
  - bundle exec rubocop -D
